### ISSUE TITLE
Ability to reset/flush parameters

### ISSUE THREAD

**Issue by Sikian** [commercetools/sphere-node-sdk#203]
This is a requests that stems from an edge-case we've encountered. This might be bad design from our side, but we consider a fail-safe like the proposed might be a good idea overall. Feedback is very welcome.

### Expected behavior
- If the parameters are populated and one wants to reset them to default, the _setDefaults (or a similar) method needs to be public.

### Actual behavior
- As _setDefaults is private, the only way to call it is by the collateral effects of fetch().

### Steps to reproduce the behavior
- Populate a service's parameters (f.e. with .page(), .perPage(), etc.)
- For some reason the query is not execution (f.e. due to miss-formed parameters or other exception arises).
- Another new request is built, but the previous one remains.

Cheers and thanks!

**Comment by jortizsao** [comment]
As @Sikian says we have seen the SDK keeps the params (some kind of state for the current query)  until 'fetch' is called . 

We were using the sphere client as singleton for our apps (one sphere client for the whole application) and due to that in some particular scenarios with asynchronous calls (even Node being single thread) two calls to the API could merge the query params within the sphere client.

We have moved from singleton to create a new sphere client for each call, but we believe this has an impact in the performance as the client needs to get a new OAuth token for each call.

Maybe only keeping the connection details as state internally in the sphere client and leaving the query builder as stateless would work, then, each call to a query builder function such as 'where', 'perPage', etc... would return the new query updated (like piping the query) or some other kind of mechanism that finally passes the query params to the 'fetch' function in order to execute it.

Thanks!!
